### PR TITLE
Persist data via sequelize

### PR DESCRIPTION
**Pull request by guillett**

### CODE REVIEW

**Comment by guillett** [comment]
I need to update that PR to rely on Enums.

**Comment by guillett** [comment]
OK, I just figured you wanted to rely on https://github.com/typeorm/typeorm

**Comment by guillett** [comment]
Not much to reuse in that PR. I close it. :)

**Comment by guillett** [comment]
I gave a migration to typeorm a try but I had to many issues with decorators and then with entity classes.

**Comment by alexisthual** [comment]
It should be clearer now, I updated the README!

**Pull request closed without merging**
